# Generated by Django 4.2.7 on 2024-01-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='highlighted',
            field=models.TextField(default='hello highlighted'),
        ),
    ]
