# Generated by Django 4.2.7 on 2024-01-22 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_simplesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcomment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
