# Generated by Django 4.2.7 on 2024-01-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.TextField()),
                ('is_Correct', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='SimpleSnippet',
        ),
    ]
