# Generated by Django 4.2.7 on 2024-01-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function_view', '0002_codesnippet_delete_simplesnippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesnippet',
            old_name='is_Correct',
            new_name='is_correct',
        ),
    ]
