# Generated by Django 4.2.7 on 2024-02-07 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('function_view', '0004_codesnippet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
